# Namespace for the application
apiVersion: v1
kind: Namespace
metadata:
  name: budgetapp

---

# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: budgetapp
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: budgetappDB
        - name: POSTGRES_USER
          value: sagar
        - name: POSTGRES_PASSWORD
          value: password123
        ports:
        - containerPort: 5432
          name: postgresql

---

# Deployment for the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetapp
  namespace: budgetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budgetapp
  template:
    metadata:
      labels:
        app: budgetapp
    spec:
      containers:
      - name: budgetapp
        image: yourimage:tag
        ports:
        - containerPort: 8080
      # Add other configuration like environment variables, volumes, etc.

---

# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: budgetapp
  namespace: budgetapp
spec:
  selector:
    app: budgetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# Ingress for accessing the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: budgetapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: budgetapp
            port:
              number: 80
