version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sagar
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: budgetappDB

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
